---
name: "GPG signing with Software Trust Manager"
description: "GPG signing automation with private key protection and multi-factor authentication (MFA)"
runs:
  using: "node16"
  main: "build/index.js"
branding:
  icon: "check-circle"
  color: "blue"
...
